ALTER TABLE kb_base_chunk ADD COLUMN IF NOT EXISTS token_count_estimated BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE kb_parent_chunk ADD COLUMN IF NOT EXISTS token_count_estimated BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE kb_chunk ADD COLUMN IF NOT EXISTS token_count_estimated BOOLEAN NOT NULL DEFAULT FALSE;
