package com.aoneng.rag.domain.kb.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.aoneng.rag.domain.kb.po.KbChunkPO;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

@Mapper
public interface KbChunkMapper extends BaseMapper<KbChunkPO> {

    int insertReturningId(KbChunkPO chunk);

    int deleteByDoc(@Param("docId") long docId);

    /**
     * Keyword (ILIKE) search across content and file name. The placeholders are pre-generated by
     * the caller.
     */
    List<Map<String, Object>> keywordSearch(@Param("kbIds") List<Long> kbIds,
                                            @Param("termClauses") List<String> termClauses,
                                            @Param("parameters") Object[] parameters,
                                            @Param("limit") int limit);
}
