package com.aoneng.rag.domain.kb.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.aoneng.rag.domain.kb.po.KbChunkPO;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

@Mapper
public interface KbChunkMapper extends BaseMapper<KbChunkPO> {

    int insertReturningId(KbChunkPO chunk);

    int updateEmbeddingId(@Param("chunkId") long chunkId,
                           @Param("embeddingId") String embeddingId);

    int updateMetadata(@Param("chunkId") long chunkId, @Param("metadata") String metadata);

    Long insertParent(@Param("docId") long docId,
                      @Param("kbId") long kbId,
                      @Param("seq") int seq,
                      @Param("content") String content,
                      @Param("pageNo") Integer pageNo,
                      @Param("tokenCount") int tokenCount);

    Long insertBase(@Param("docId") long docId,
                    @Param("kbId") long kbId,
                    @Param("seq") int seq,
                    @Param("content") String content,
                    @Param("pageNo") Integer pageNo,
                    @Param("tokenCount") int tokenCount,
                    @Param("blockType") String blockType,
                    @Param("metadata") String metadata);

    int updateParentEmbeddingId(@Param("parentId") long parentId, @Param("embeddingId") String embeddingId);

    Map<String, Object> selectParent(@Param("id") long id);

    int deleteByDoc(@Param("docId") long docId);

    int deleteParentsByDoc(@Param("docId") long docId);

    int deleteBaseByDoc(@Param("docId") long docId);

    /**
     * Keyword (ILIKE) search across content and file name. The placeholders are pre-generated by
     * the caller.
     */
    List<Map<String, Object>> keywordSearch(@Param("kbIds") List<Long> kbIds,
                                            @Param("terms") List<String> terms,
                                            @Param("limit") int limit);
}
