spring:
  config:
    activate:
      on-profile: dev
  jpa:
    show-sql: true

logging:
  level:
    root: INFO
    com.aoneng.rag: DEBUG
    org.springframework.security: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
